# Generated by Django 4.0 on 2021-12-21 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Market', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyprice',
            name='date_created',
            field=models.DateField(auto_now=True),
        ),
    ]
