# Generated by Django 3.2.10 on 2024-07-20 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Market', '0002_alter_dailyprice_date_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trackedproduct',
            old_name='start_url',
            new_name='commodity',
        ),
        migrations.RenameField(
            model_name='trackedproduct',
            old_name='title',
            new_name='container',
        ),
    ]
