name: Continuous Integration
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install Dependencies
        run: |
          pipenv install

      - name: Pull Latest Master File
        run: |
          # Write the necessary commands to pull the latest master file to the deploy key server
