# Generated by Django 4.0 on 2021-12-18 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailySale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeliveredProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('unit', models.CharField(max_length=255)),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=9)),
                ('content', models.CharField(max_length=255)),
                ('content_cost', models.DecimalField(decimal_places=2, max_digits=9)),
                ('transport', models.DecimalField(decimal_places=2, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name='ItemSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('payment', models.DecimalField(decimal_places=2, max_digits=9)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='Sales.product')),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_note_reference', models.CharField(max_length=255)),
                ('send_date', models.DateField(auto_now=True)),
                ('delivered_products', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Sales.deliveredproducts')),
                ('market', models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='market_sold_at', to='Sales.market')),
                ('sales', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Sales.dailysale')),
            ],
        ),
        migrations.AddField(
            model_name='deliveredproducts',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Sales.product'),
        ),
        migrations.AddField(
            model_name='dailysale',
            name='sold_items',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Sales.itemsale'),
        ),
    ]
