# Generated by Django 4.0 on 2021-12-19 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailysale',
            name='sold_items',
        ),
        migrations.RemoveField(
            model_name='deliverynote',
            name='delivered_products',
        ),
        migrations.AddField(
            model_name='deliveredproducts',
            name='delivery_note',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='Sales.deliverynote'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itemsale',
            name='sale',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='Sales.dailysale'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='deliverynote',
            name='sales',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Sales.dailysale'),
        ),
    ]
