# Generated by Django 4.0 on 2021-12-19 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0002_remove_dailysale_sold_items_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverynote',
            name='sales',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Sales.dailysale'),
        ),
    ]
