# Generated by Django 4.0 on 2021-12-19 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0003_alter_deliverynote_sales'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverynote',
            name='delivery_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='itemsale',
            name='sale_date',
            field=models.DateField(auto_now=True),
        ),
    ]
