# Generated by Django 4.0 on 2021-12-19 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0004_deliverynote_delivery_date_itemsale_sale_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverynote',
            name='delivery_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='deliverynote',
            name='market',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='market_sold_at', to='Sales.market'),
        ),
        migrations.AlterField(
            model_name='itemsale',
            name='sale_date',
            field=models.DateField(),
        ),
    ]
