# Generated by Django 4.0 on 2021-12-19 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0005_alter_deliverynote_delivery_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemsale',
            name='sale_date',
        ),
        migrations.AlterField(
            model_name='dailysale',
            name='sale_date',
            field=models.DateField(),
        ),
    ]
