# Generated by Django 4.0 on 2021-12-19 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0006_remove_itemsale_sale_date_alter_dailysale_sale_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemsale',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='sold_items', to='Sales.dailysale'),
        ),
    ]
