# Generated by Django 4.0 on 2021-12-19 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0007_alter_itemsale_sale'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliverynote',
            name='sales',
        ),
        migrations.AddField(
            model_name='dailysale',
            name='delivery_note',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='delivery_sales', to='Sales.deliverynote'),
            preserve_default=False,
        ),
    ]
