# Generated by Django 4.0 on 2021-12-19 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0008_remove_deliverynote_sales_dailysale_delivery_note'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DeliveredProducts',
            new_name='DeliveredProduct',
        ),
    ]
