# Generated by Django 4.0 on 2021-12-19 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0009_rename_deliveredproducts_deliveredproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemsale',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Sales.product'),
        ),
    ]
