# Generated by Django 4.0 on 2021-12-19 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0010_alter_itemsale_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemsale',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Sales.product'),
        ),
        migrations.AlterField(
            model_name='itemsale',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sold_items', to='Sales.dailysale'),
        ),
    ]
