# Generated by Django 4.0 on 2021-12-20 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0011_alter_itemsale_product_alter_itemsale_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailysale',
            name='delivery_note',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='delivery_sales', to='Sales.deliverynote'),
        ),
        migrations.AlterField(
            model_name='deliverynote',
            name='market',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='market_sold_at', to='Sales.market'),
            preserve_default=False,
        ),
    ]
