# Generated by Django 4.0 on 2021-12-20 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0012_alter_dailysale_delivery_note_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailysale',
            name='delivery_note',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_sales', to='Sales.deliverynote'),
        ),
        migrations.AlterField(
            model_name='deliveredproduct',
            name='delivery_note',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sales.deliverynote'),
        ),
        migrations.AlterField(
            model_name='deliveredproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sales.product'),
        ),
        migrations.AlterField(
            model_name='deliverynote',
            name='market',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='market_sold_at', to='Sales.market'),
        ),
    ]
