# Generated by Django 4.0 on 2021-12-20 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0013_alter_dailysale_delivery_note_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemsale',
            name='payment',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
    ]
